services:
  cipettelens-dev:
    build: .
    ports:
      - "${FLASK_PORT:-5001}:${FLASK_PORT:-5001}"
      - "5678:5678" # For debugger
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TARGET_REPOSITORIES=${TARGET_REPOSITORIES}
      - FLASK_DEBUG=True
      - FLASK_PORT=${FLASK_PORT:-5001}
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - /app/.venv # Exclude virtual environment
      - ./logs:/app/logs
      - ./db:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["uv", "run", "web"]
    networks:
      - cipettelens-dev-network

networks:
  cipettelens-dev-network:
    driver: bridge