name: Weekly Security Scan

on:
  schedule:
    - cron: "0 3 * * 1"  # Weekly on Monday at 3 AM UTC
  workflow_dispatch:  # Manual trigger

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.8.22"

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run security scan
        run: |
          uv add bandit[toml] safety
          uv run bandit -r cipettelens/ -f txt
          uv run safety check
          uv audit
